### ISSUE TITLE
ssl_helper not installed

### ISSUE THREAD

**Issue by uninsidex** [meefik/busybox#74] opened 2019-01-17 03:44 UTC
cp: can't stat '': No such file or directory fail

**Comment by licaon-kter** [comment] 2019-11-05 13:59
The F-Droid build is missing ssl_helper.

**Comment by licaon-kter** [comment] 2019-11-05 14:01
/duplicate of https://github.com/meefik/busybox/issues/67 I guess

**Closed** 2019-12-29 21:10 UTC
